
DROP TABLE PERSON CASCADE;
DROP TABLE ADDRESS CASCADE;
DROP TABLE ADDRESS_TYPE CASCADE;
DROP TABLE BILLING_INFO CASCADE;
DROP TABLE CARD_TYPE CASCADE;
DROP TABLE USER_REVIEW CASCADE;
DROP TABLE LOGIN CASCADE;
DROP TABLE AUCTION CASCADE;
DROP TABLE AUCTION_STATUS CASCADE;
DROP TABLE ITEM_CATEGORY CASCADE;
DROP TABLE ITEM_CONDITION CASCADE;
DROP TABLE BID CASCADE;
DROP TABLE WATCHED_ITEMS CASCADE;
