-- __________________  Setup data __________________
INSERT INTO ADDRESS_TYPE VALUES (1, 'Billing');
INSERT INTO ADDRESS_TYPE VALUES (2, 'Shipping');

INSERT INTO CARD_TYPE VALUES (1, 'Visa');
INSERT INTO CARD_TYPE VALUES (2, 'Mastercard');
INSERT INTO CARD_TYPE VALUES (3, 'Discover');

INSERT INTO ITEM_CONDITION VALUES(1, 'New');
INSERT INTO ITEM_CONDITION VALUES(2, 'Very Good');
INSERT INTO ITEM_CONDITION VALUES(3, 'Good');
INSERT INTO ITEM_CONDITION VALUES(4, 'Fair');
INSERT INTO ITEM_CONDITION VALUES(5, 'Poor');

INSERT INTO AUCTION_STATUS VALUES (1, 'Open');
INSERT INTO AUCTION_STATUS VALUES (2, 'Cancelled');
INSERT INTO AUCTION_STATUS VALUES (3, 'Closed');
INSERT INTO AUCTION_STATUS VALUES (4, 'Failed');

INSERT INTO ITEM_CATEGORY VALUES (1, 'Antiques');
INSERT INTO ITEM_CATEGORY VALUES (2, 'Art & Collectibles');
INSERT INTO ITEM_CATEGORY VALUES (3, 'Books & Movies & Music');
INSERT INTO ITEM_CATEGORY VALUES (4, 'Cars');
INSERT INTO ITEM_CATEGORY VALUES (5, 'Clothing');
INSERT INTO ITEM_CATEGORY VALUES (6, 'Computers & Electronics');
INSERT INTO ITEM_CATEGORY VALUES (7, 'Home');
INSERT INTO ITEM_CATEGORY VALUES (8, 'Jewelry');
INSERT INTO ITEM_CATEGORY VALUES (9, 'Musical Instruments');
INSERT INTO ITEM_CATEGORY VALUES (10, 'Tools');
INSERT INTO ITEM_CATEGORY VALUES (11, 'Toys');
